spring:
  application:
    name: goo99

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username:
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: Z29vOTktc3ByaW5nLWJvb3QtZGl2aWRlbmQtcHJvamVjdC10dXRvcmlhbC1qd3Qtc2VjcmV0LWtleQo=


scheduler:
  scrap:
    yahoo: "0 0 0 * * *"