spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dividenddb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dividenduser
    password: dividend

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true